volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge

services:
  # Frontend Service
  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map container port (80, served by Nginx) to host port 3000
    depends_on:
      - backend 
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app_network

  # Backend Service
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Map container port 5000 to host port 5001
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env  # Loads REACT_APP_API_URL and MONGO_URI from the root .env file
    environment:
      - PORT=5000
    networks:
      - app_network

  # MongoDB Service
  mongo:
    container_name: mongo-container
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network
