name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log into Docker Hub using the secrets added
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Step 4: Build the frontend Docker image and push it to Docker Hub
      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopssec-frontend:latest

      # Step 5: Build the backend Docker image and push it to Docker Hub
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopssec-backend:latest
