name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Frontend Steps
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Audit Frontend Dependencies
        working-directory: ./frontend
        run: npm audit --audit-level=moderate

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      - name: Lint Frontend Code
        working-directory: ./frontend
        run: npm run lint

      - name: Cache Frontend Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-

      # Backend Steps
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Audit Backend Dependencies
        working-directory: ./backend
        run: npm audit --audit-level=moderate

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Lint Backend Code
        working-directory: ./backend
        run: npm run lint

      # Debug: List frontend directory for verification
      - name: Debug Frontend Directory
        run: |
          ls -al frontend/
          cat frontend/package.json

      # Docker Build Steps
      - name: Build Frontend Image
        run: |
          docker build -t liolax/my-devopssec-ca-app:frontend-${{ env.IMAGE_TAG }} -f frontend/Dockerfile ./frontend

      - name: Build Backend Image
        run: |
          docker build -t liolax/my-devopssec-ca-app:backend-${{ env.IMAGE_TAG }} -f backend/Dockerfile ./backend

      # Docker Hub Login & Push Steps
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Frontend Image
        run: |
          docker push liolax/my-devopssec-ca-app:frontend-${{ env.IMAGE_TAG }}

      - name: Push Backend Image
        run: |
          docker push liolax/my-devopssec-ca-app:backend-${{ env.IMAGE_TAG }}
